SELECT 'hello, PG';

DROP TABLE IF EXISTS rank CASCADE;
DROP TABLE IF EXISTS assignement CASCADE;
DROP TABLE IF EXISTS sailor CASCADE;
DROP TABLE IF EXISTS ship CASCADE;
DROP TABLE IF EXISTS fleet CASCADE;

CREATE TABLE fleets (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(50) NOT NULL
);

CREATE TABLE ships (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(50) NOT NULL,
  date_built INTEGER NOT NULL
  assign_id INTEGER NOT NULL
);

CREATE TABLE sailors (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(50) NOT NULL,
  date_of_birth INTEGER NOT NULL,
  assign_id INTEGER NOT NULL
);

CREATE TABLE assignements (
  id SERIAL PRIMARY KEY NOT NULL,
  start_date INTEGER NOT NULL,
  end_date INTEGER NOT NULL,
  rank INTEGER NOT NULL,
  rank_id INTEGER NOT NULL REFERENCES ranks(id) ON DELETE CASCADE,
  sailor_id INTEGER NOT NULL REFERENCES sailors(id) ON DELETE CASCADE,
  ship_id INTEGER NOT NULL REFERENCES ships(id) ON DELETE CASCADE
);

CREATE TABLE ranks (
  name VARCHAR(50) NOT NULL
  id SERIAL PRIMARY KEY NOT NULL
);